import subprocess

template = """
#pragma once

// GENERATED BY git-version.py

#define VERSION "%s"
"""

version = subprocess.run(["git", "describe", "--tags", "--dirty"], stdout=subprocess.PIPE).stdout.decode('utf-8').strip()

print("Firmware version: " + version)

print(template.strip() % version, file=open("include/version.h", "w"))
